### PR TITLE
fix(Whatsapp): Fix message "WhatsApp works with Google Chrome 36+"

### PR DESCRIPTION
**Pull request by Pablo1107**
As title says. Whatsapp has an issue in recent versions of Franz. The instructions in the official site says to update the recipes for that service. As that overrides the themes, and for what it seems only the index.js needs to be updated for it to work and have the dark theme, this is the file I change.

### CODE REVIEW

**Comment by MikeDabrowski** [comment]
Great, thank you. Could you add link to the official info about this issue?

EDIT: I think I finally got it: https://github.com/meetfranz/recipe-whatsapp/commit/7bfb9bbfc8076e8e9189c5c130919fc5a11c0c1c

**Comment by Pablo1107** [comment]
@MikeDabrowski sorry for reading this late, I change my github email and forgot to check it, but you got the issue. I don't know if you updated this repo correctly but I send a PR to solve it #5

**Comment by MikeDabrowski** [comment]
Ok, I don't use whatsapp, and I don't really have time to check it. Are you 100% sure this code will work and solve original issue? Maybe try to checkout hard master, remove redundant files, checkout #5 and test again. I think it should work.

**Comment by Pablo1107** [comment]
@MikeDabrowski I now make sure I was using the repo inside the recipes folder so its one to one with master, and no problems yet.

**Pull request merged**
